services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Oveleon\ContaoPropstackApiBundle\:
        resource: '../../'
        exclude: '../../{Model,DependencyInjection,Resources,**/Options}'

    Oveleon\ContaoPropstackApiBundle\EventListener\ApiExceptionSubscriber:
        arguments: []
        tags:
            - { name: kernel.event_subscriber }
